#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro package install ${PACKAGE_NAME} <args...>"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  install
  if [ $? -eq 0 ]; then
    log::success "install ${PACKAGE_NAME} success."
    exit 0
  else
    log::error "install ${PACKAGE_NAME} failed."
    exit 1
  fi
}

run() {
  core "$@"
}

if [ "$1" = "ONE_LINE" ]; then
  command -v zmicro >>/dev/null 2>&1
  if [ $? -ne 0 ]; then
    curl -o- https://raw.githubusercontent.com/zcorky/zmicro/master/install | sh
  fi

  zmicro package install mtg
else
  set -e
  
  run "$@"
fi
