#!/bin/bash

os::inquirer PLUGIN_NAME "text" "Input Plugin Name" true
os::inquirer PLUGIN_DESCRIPTION "text" "Input Plugin Description" true
os::inquirer PLUGIN_VERSION "text" "Input Plugin Version" true "v0.0.0"
