#!/bin/bash

name() {
  local version=$(plugin::get_version $PLUGIN_VM_NAME)
  echo "Virtual Machine Manager ($(color::success $version))"
}

description() {
  echo "VM is a tool for managing virtual machines, based on multipass and lima."
}

usage() {
  echo "Usage:"
  echo "  zvm start <name>         - Start a virtual machine"
  echo "  zvm stop <name>          - Stop a virtual machine"
  echo "  zvm restart <name>       - Restart a virtual machine"
  echo "  zvm remove <name>        - Remove a virtual machine"
  echo "  zvm exec <name>          - Connect shell to a virtual machine"
  echo "  zvm inspect <name>       - Inspect a virtual machine"
  echo "  zvm help                 - Show help"
}

example() {
  echo "Example:"
  echo "  zvm start test01"
}

core() {
  name
  echo ""
  description
  echo ""
  usage
  echo ""
  example
}

run() {
  core $@
}

run $@
