#!/bin/bash

name() {
  local version=$(plugin::get_version $PLUGIN_{{ .PLUGIN_NAME | ToUpper  }}_NAME)
  echo "{{.PLUGIN_NAME}} ($(color::success $version))"
}

description() {
  echo "{{.PLUGIN_DESCRIPTION}}"
}

usage() {
  echo "Usage:"
  echo "  zmicro {{.PLUGIN_NAME}} start <name>         - Start a virtual machine"
  echo "  zmicro {{.PLUGIN_NAME}} stop <name>          - Stop a virtual machine"
  echo "  zmicro {{.PLUGIN_NAME}} restart <name>       - Restart a virtual machine"
  echo "  zmicro {{.PLUGIN_NAME}} remove <name>        - Remove a virtual machine"
  echo "  zmicro {{.PLUGIN_NAME}} exec <name>          - Connect shell to a virtual machine"
  echo "  zmicro {{.PLUGIN_NAME}} inspect <name>       - Inspect a virtual machine"
  echo "  zmicro {{.PLUGIN_NAME}} help                 - Show help"
}

example() {
  echo "Example:"
  echo "  zmicro {{.PLUGIN_NAME}} start test01"
}

core() {
  name
  echo ""
  description
  echo ""
  usage
  echo ""
  example
}

run() {
  core $@
}

run $@
