#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro {{.PLUGIN_NAME}} list"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  multipass list
}

run() {
  core $@
}

run $@
