#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro {{.PLUGIN_NAME}} remove <name>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local name=$1
  if [ -z "$name" ]; then
    log::error "[$(timestamp)] name is required"
    exit 1
  fi

  multipass delete $name
  multipass purge
}

run() {
  core $@
}

run $@
