#!/bin/bash

help() {
  echo "Usage:"
  echo "  zvm restart <name>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local name=$1
  if [ -z "$name" ]; then
    log::error "[$(timestamp)] name is required"
    exit 1
  fi

  multipass restart $name
}

run() {
  core $@
}

run $@
