#!/bin/bash

# {{.PLUGIN_NAME}}::os get the system os
{{.PLUGIN_NAME}}::os() {
  local os="linux"

  uname -a | grep "Darwin" >>/dev/null 2>&1
  if [ $? == 0 ]; then
    os=darwin
  fi

  echo $os
}


export -f {{.PLUGIN_NAME}}::os
